function botNetwork = update_bot_info(curPos, dest, route, explore_map, botNetwork, ii)
        [botNetwork.bots(ii).curPos,...
         botNetwork.bots(ii).dest,...
         botNetwork.bots(ii).route,...
         botNetwork.explore_map] = deal(curPos, dest, route, explore_map);
end

