function [curPos, dest, route, explore_map, sensorInput] = extract_bot_info(botNetwork, ii)
    [curPos, dest, route, explore_map] = ...
        deal(botNetwork.bots(ii).curPos,...
             botNetwork.bots(ii).dest,...
             botNetwork.bots(ii).route,...
             botNetwork.explore_map);
end

